# Generated by Django 4.2.27 on 2025-12-09 13:29

import core.models
import core.utils
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DadosSolicPesquisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.localdate)),
                ('acao_realizada', models.CharField(max_length=80, verbose_name='Qual atividade será realizada na UC?')),
                ('unidade_cons', models.CharField(max_length=80, verbose_name='Unidade(s) de conservação onde será(ão) realizada(s) a atividade')),
                ('tipo_solic', models.CharField(choices=[('NA', 'Selecione'), ('AUTORIZAÇÃO', 'Autorização'), ('RENOVACAO', 'Renovação')], max_length=20, verbose_name='Tipo de solicitação')),
                ('foto', models.CharField(choices=[('NA', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Fotografia e imagens da UC?')),
                ('licenca_inst', models.CharField(choices=[('NA', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Licença de instituição responsavel?')),
                ('inicio_atividade', models.DateField(default=django.utils.timezone.localdate)),
                ('final_atividade', models.DateField(default=django.utils.timezone.localdate)),
                ('retorno_comuni', models.CharField(choices=[('NA', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Retorno para a comunidade')),
                ('area_atuacao', models.CharField(choices=[('NA', 'Selecione'), ('FAUNA', 'Fauna'), ('FLORA', 'Flora'), ('ECOLOGIA', 'Ecologia'), ('GEOLOGIA', 'Geologia'), ('SOCIOECONOMIA', 'Socioeconomia'), ('ARQUEOLOGIA', 'Arqueologia'), ('TURISMO', 'Turismo'), ('RECURSOS HIDRICOS', 'Recursos hidricos'), ('EDUCAÇÃO AMBIENTAL', 'Educação Ambiental'), ('CAVIDADES NATURAIS', 'Cavidades Naturais'), ('OUTROS', 'Outros')], max_length=100, verbose_name='Aréa de atuação')),
                ('status', models.BooleanField(default=False)),
                ('user_solic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solic_pesquisa',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, validators=[core.utils.validador_cpf], verbose_name='CPF')),
                ('instituicao', models.CharField(max_length=80, verbose_name='Instiuições')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('NA', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('estado', models.CharField(choices=[('NA', 'Selecione'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20)),
                ('municipio', models.CharField(choices=[('NA', 'Selecione'), ('ACRELANDIA', 'Acrelândia'), ('ASSIS_BRASIL', 'Assis Brasil'), ('BRASILEIA', 'Brasiléia'), ('BUJARI', 'Bujari'), ('CAPIXABA', 'Capixaba'), ('CRUZEIRO_SUL', 'Cruzeiro do Sul'), ('EPITACIOLANDIA', 'Epitaciolândia'), ('FEIJO', 'Feijó'), ('JORDAO', 'Jordão'), ('MANOEL_URB', 'Manoel Urbano'), ('MARECHAL_THAU', 'Marechal Thaumaturgo'), ('MANCIO_LIMA', 'Mâncio Lima'), ('PLACIDO_CAS', 'Plácido de Castro'), ('PORTO_ACRE', 'Porto Acre'), ('PORTO_WALT', 'Porto Walter'), ('RIO_BRANCO', 'Rio Branco'), ('RODRIGUES_ALV', 'Rodrigues Alves'), ('SANTA_ROSA', 'Santa Rosa do Purus'), ('SENA_MADURE', 'Sena Madureira'), ('SENADOR_GUIOM', 'Senador Guiomard'), ('TARAUACA', 'Tarauacá'), ('XAPURI', 'Xapuri')], max_length=30)),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('celular', models.CharField(max_length=13, validators=[core.utils.check_number])),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('org_emiss', models.CharField(max_length=30, verbose_name='Orgão emissor(RG)')),
                ('cpf', models.CharField(max_length=11, validators=[core.utils.validador_cpf], verbose_name='CPF')),
                ('telefone_fixo', models.CharField(blank=True, default='NA', max_length=8, null=True)),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('profis', models.CharField(max_length=30, verbose_name='Profissão/Ocupação')),
                ('email', models.CharField(blank=True, default='NA', max_length=80, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_pessoais',
            },
        ),
        migrations.CreateModel(
            name='ArquivosRelFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=core.models.get_upload_path)),
                ('upado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arq_pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
    ]
