# Generated by Django 5.2.8 on 2025-11-21 13:02

import core.utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')])),
                ('estado', models.CharField(choices=[('', 'Selecione'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')])),
                ('municipio', models.CharField(choices=[('', 'Selecione'), ('AC', 'Acrelândia'), ('AC', 'Assis Brasil'), ('AC', 'Brasiléia'), ('AC', 'Bujari'), ('AC', 'Capixaba'), ('AC', 'Cruzeiro do Sul'), ('AC', 'Epitaciolândia'), ('AC', 'Feijó'), ('AC', 'Jordão'), ('AC', 'Manoel Urbano'), ('AC', 'Marechal Thaumaturgo'), ('AC', 'Mâncio Lima'), ('AC', 'Plácido de Castro'), ('AC', 'Porto Acre'), ('AC', 'Porto Walter'), ('AC', 'Rio Branco'), ('AC', 'Rodrigues Alves'), ('AC', 'Santa Rosa do Purus'), ('AC', 'Sena Madureira'), ('AC', 'Senador Guiomard'), ('AC', 'Tarauacá'), ('AC', 'Xapuri')])),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('celular', models.CharField(max_length=13, validators=[core.utils.check_number])),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('org_emiss', models.CharField(max_length=30, verbose_name='Orgão emissor')),
                ('cpf', models.CharField(max_length=11, validators=[core.utils.validador_cpf], verbose_name='CPF')),
                ('telefone_fixo', models.CharField(blank=True, max_length=8, null=True)),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('profis', models.CharField(max_length=30, verbose_name='Profissão/Ocupação')),
                ('email', models.CharField(blank=True, default='N/A', max_length=80, null=True)),
            ],
            options={
                'db_table': 'dados_pessoais',
            },
        ),
        migrations.CreateModel(
            name='DadosSolicPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now)),
                ('acao_realizada', models.CharField(max_length=80, verbose_name='Ação realizada')),
                ('unidade_cons', models.CharField(choices=[('', 'Selecione'), ('AUTORIZAÇÃO', 'Autorização'), ('RENOVACAO', 'Renovação')], max_length=80, verbose_name='Unidade de conservação')),
                ('tipo_solic', models.CharField(verbose_name='Tipo de solicitação')),
                ('rel_final', models.CharField(max_length=500, verbose_name='Relatorio final de resultados')),
                ('foto', models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], verbose_name='Fotografia e imagens da UC?')),
                ('licenca_inst', models.CharField(verbose_name='Licença de instituição responsavel')),
                ('periodo_dur', models.CharField(verbose_name='Periodo de duração da atividade')),
                ('retorno_comuni', models.CharField(verbose_name='Retorno para a comunidade')),
                ('area_atuacao', models.CharField(choices=[('', 'Selecione'), ('FAUNA', 'Fauna'), ('FLORA', 'Flora'), ('ECOLOGIA', 'Ecologia'), ('GEOLOGIA', 'Geologia'), ('SOCIOECONOMIA', 'Socioeconomia'), ('ARQUEOLOGIA', 'Arqueologia'), ('TURISMO', 'Turismo'), ('RECURSOS HIDRICOS', 'Recursos hidricos'), ('EDUCAÇÃO AMBIENTAL', 'Educação Ambiental'), ('CAVIDADES NATURAIS', 'Cavidades Naturais'), ('OUTROS', 'Outros')], verbose_name='Aréa de atuação')),
            ],
            options={
                'db_table': 'solic_pesquisa',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
