# Generated by Django 5.2.8 on 2025-11-21 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='uuid',
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadossolicpesquisa',
            name='final_atividade',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='dadossolicpesquisa',
            name='inicio_atividade',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='dadossolicpesquisa',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='municipio',
            field=models.CharField(choices=[('', 'Selecione'), ('ACRELANDIA', 'Acrelândia'), ('ASSIS_BRASIL', 'Assis Brasil'), ('BRASILEIA', 'Brasiléia'), ('BUJARI', 'Bujari'), ('CAPIXABA', 'Capixaba'), ('CRUZEIRO_SUL', 'Cruzeiro do Sul'), ('EPITACIOLANDIA', 'Epitaciolândia'), ('FEIJO', 'Feijó'), ('JORDAO', 'Jordão'), ('MANOEL_URB', 'Manoel Urbano'), ('MARECHAL_THAU', 'Marechal Thaumaturgo'), ('MANCIO_LIMA', 'Mâncio Lima'), ('PLACIDO_CAS', 'Plácido de Castro'), ('PORTO_ACRE', 'Porto Acre'), ('PORTO_WALT', 'Porto Walter'), ('RIO_BRANCO', 'Rio Branco'), ('RODRIGUES_ALV', 'Rodrigues Alves'), ('SANTA_ROSA', 'Santa Rosa do Purus'), ('SENA_MADURE', 'Sena Madureira'), ('SENADOR_GUIOM', 'Senador Guiomard'), ('TARAUACA', 'Tarauacá'), ('XAPURI', 'Xapuri')]),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='acao_realizada',
            field=models.CharField(max_length=80, verbose_name='Qual atividade será realizada na UC?'),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='licenca_inst',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], verbose_name='Licença de instituição responsavel?'),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='tipo_solic',
            field=models.CharField(choices=[('', 'Selecione'), ('AUTORIZAÇÃO', 'Autorização'), ('RENOVACAO', 'Renovação')], verbose_name='Tipo de solicitação'),
        ),
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='unidade_cons',
            field=models.CharField(max_length=80, verbose_name='Unidade(s) de conservação onde será(ão) realizada(s) a atividade'),
        ),
    ]
