# Generated by Django 5.2.8 on 2025-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dadospessoais_uuid_dadospessoais_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
