# Generated by Django 5.2.8 on 2025-11-21 16:49

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dadossolicpesquisa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, validators=[core.utils.validador_cpf], verbose_name='CPF')),
                ('instituicao', models.CharField(verbose_name='Instiuições')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
    ]
