# Generated by Django 5.2.8 on 2025-11-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dadossolicpesquisa_id_membroequipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadossolicpesquisa',
            name='rel_final',
        ),
    ]
