# Generated by Django 5.2.8 on 2025-11-24 18:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_dadossolicpesquisa_rel_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosRelFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='rel_final_pesq')),
                ('upado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arq_pesquisa', to='core.dadossolicpesquisa')),
            ],
        ),
    ]
