# Generated by Django 5.2.8 on 2025-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_arquivosrelfinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadossolicpesquisa',
            name='periodo_dur',
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='org_emiss',
            field=models.CharField(max_length=30, verbose_name='Orgão emissor(RG)'),
        ),
    ]
