# Generated by Django 5.2.8 on 2025-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_dadossolicpesquisa_periodo_dur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
