# Generated by Django 5.2.8 on 2025-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dadossolicpesquisa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossolicpesquisa',
            name='retorno_comuni',
            field=models.CharField(choices=[('', 'Selecione'), ('SIM', 'Sim'), ('NAO', 'Não')], verbose_name='Retorno para a comunidade'),
        ),
    ]
